version: '2'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 123.0.0.0/16

services:
  httpd-php:
    build:
      context: ./docker/httpd-php
    container_name: httpd
    environment:
      APACHE_LOG_DIR: /usr
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
      - ./docker/httpd-php/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/httpd-php/apache2/envvars:/etc/apache2/envvars
      - ./docker/httpd-php/apache2/configurations:/etc/apache2/conf-enabled
      - ./docker/httpd-php/apache2/hosts:/etc/apache2/sites-enabled
      - ./docker/httpd-php/php/php.ini:/etc/php/7.4/apache2/php.ini
      - ./docker/var/log/apache2:/var/log/apache2
    restart: always
    networks:
      default:
        ipv4_address: 123.0.0.10
  mysql:
    image: mysql:5.7
    container_name: mysql
    # ports:
    #    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/var/data/mysql:/var/lib/mysql
      - ./docker/var/log/mysql:/var/log/mysql
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
    restart: always
    networks:
      default:
        ipv4_address: 123.0.0.12
