FROM debian:latest

RUN apt update && apt -y upgrade && apt -y install \
    curl \
    wget \
    vim

RUN apt -y install lsb-release apt-transport-https ca-certificates
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

RUN apt update && apt install -y \
        apache2 \
        php7.4 \
        php7.4-mysql \
        php7.4-xml \
        php7.4-mbstring \
        libapache2-mod-php7.4


RUN a2enmod php7.4
RUN a2enmod rewrite
RUN a2dissite 000-default

RUN sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php/7.4/apache2/php.ini
RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php/7.4/apache2/php.ini

COPY / /var/www/html
COPY /docker/httpd-php/apache2/apache2.conf /etc/apache2/apache2.conf
COPY /docker/httpd-php/apache2/envvars /etc/apache2/envvars
COPY /docker/httpd-php/apache2/configurations /etc/apache2/conf-enabled
COPY /docker/httpd-php/apache2/hosts /etc/apache2/sites-enabled
COPY /docker/httpd-php/php/php.ini /etc/php/7.4/apache2/php.ini

WORKDIR /var/www/html
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"

RUN php composer.phar install

RUN service apache2 restart

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

EXPOSE 80

CMD /usr/sbin/apache2ctl -D FOREGROUND